version: "3.3"

services:
  burnout-backend:
    container_name: burnout-backend
    image: ghcr.io/burnstopper/burnout-backend:2.6
    networks:
      - local-net
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
  frontend:
    container_name: frontend
    image: ghcr.io/burnstopper/burnout-frontend:2.7
    networks:
      - local-net
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  local-net:
    driver: bridge
