version: "3.3"

services:
  burnout-backend:
    container_name: burnout-backend
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - local-net

  burnout-nginx:
    container_name: burnout-nginx
    build:
      context: ./
      args:
        BURNOUT_HOST_NAME: ${BURNOUT_HOST_NAME}
    environment:
      BURNOUT_HOST_NAME: ${BURNOUT_HOST_NAME}
      BURNOUT_PORT: ${BURNOUT_PORT}
    ports:
      - "${BURNOUT_PORT}:${BURNOUT_PORT}"
    depends_on:
      - burnout-backend
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
